---
- hosts: webservers
  remote_user: root
  become: yes
  vars:
    pkg: httpd
  tasks:
    - name: installing httpd
      yum: name={{pkg}} state=installed
    - name: copy index.html file
      copy: src=index.html dest=/var/www/html
    - name: start httpd
      service: name={{pkg}} state=started
